version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    command: --admin-password '$$2y$$05$$cEhcu84AGRy5X7E6cxfBrOj0G3k563gPNB67fjjAFUYYCAoqdQznW'
    ports:
      - 9000:9000
      - 80:9000


  raspotify:
    image: flaviostutz/rpi-spotify:1.6.1
    devices:
      - "/dev/snd"
    environment:
      - SPOTIFY_NAME=Raspotify
    network_mode: "host"
    restart: always

  earnapp:
    image: fazalfarhan01/earnapp
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./etc:/etc/earnapp
    environment:
      - EARNAPP_UUID=sdk-node-f6a6c5b3
