version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.15.1
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    command: --admin-password '$$2y$$05$$cEhcu84AGRy5X7E6cxfBrOj0G3k563gPNB67fjjAFUYYCAoqdQznW'
    ports:
      - 9000:9000
    networks:
      - caddy

  raspotify:
    image: flaviostutz/rpi-spotify:1.6.1
    container_name: raspotify
    devices:
      - "/dev/snd"
    environment:
      - SPOTIFY_NAME=Raspotify
    restart: always
    network_mode: host

  # TODO configure with env vars
  syncthing:
    image: funkyfuture/rpi-syncthing
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - UID=1000
      - GID=1000
      - USER_NAME=mathetes
      - GUI_PASSWORD_PLAIN=2112
      - GUI_USERNAME=mathetes
      # - GUI_ADDRESS=[::]:8384
    volumes:
      - /media/syncthing/appdata/config:/syncthing/config
      - /media/syncthing/data:/syncthing/data
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped


  # transmission:
  #   image: linuxserver/transmission
  #   container_name: transmission
  #   environment:
  #     - PUID=1000 # User id
  #     - PGID=1000 # Group id
  #     - TZ=America/Santiago # Your current timezone
  #   volumes:
  #     - /media/HDD/.transmission:/config # Change this to your docker config folder
  #     - /media/HDD/media/:/download # Change this to your download folder
  #   ports:
  #     - 9091:9091 # Web UI port
  #     - 51413:51413 # Torrent port (TCP)
  #     - 51413:51413/udp # Torrent port (UDP)
  #   restart: unless-stopped # This makes sure that the application restarts when it crashes
  #   networks:
  #     - caddy

  # plex:
  #   image: greensheep/plex-server-docker-rpi:latest
  #   restart: unless-stopped
  #   container_name: plex
  #   ports:
  #     - 32400:32400/tcp
  #     - 3005:3005/tcp
  #     - 8324:8324/tcp
  #     - 32469:32469/tcp
  #     - 1900:1900/udp
  #     - 32410:32410/udp
  #     - 32412:32412/udp
  #     - 32413:32413/udp
  #     - 32414:32414/udp

  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=America/Santiago # Your current timezone
  #     - PLEX_CLAIM=claim-abGqqUeyeUewcN_5q58y
  #     - HOSTNAME=”PlexServer”
  #     - SYSCALL_MAX_ENABLED=1

  #   volumes:
  #     - /media/HDD/.plex/config:/config
  #     - /media/HDD/.plex/transcodes:/transcode
  #     - /media/HDD/.plex/
  #     - /media/HDD/media:/media
  #   networks:
  #     - caddy


  # caddy:
  #   image: caddy:alpine
  #   container_name: caddy
  #   ports:
  #     - 80:80
  #     - 443:443
  #   environment:
  #     - CADDY_INGRESS_NETWORKS=caddy
  #   networks:
  #     - caddy
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     # - $PWD/site:/srv
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   restart: unless-stopped

# volumes:
#   caddy_data:
#     external: true
#   caddy_config:


networks:
  caddy:
    external: true
